id: PB43476E9
initial_creation_type: input
source_metadata:
  title: Brahmasūtra2 with Vācaspati's Bhāmatī (a subcommentary on Śaṃkara's Śārīrakamīmāṃsābhāṣya)
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:55:00.415687'
last_modified_at: '2022-03-09T14:55:00.415701'
